name: Add Rules to Cloudflare Gateway
on:
  push:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  run:
    name: Cloudflare Gateway
    permissions: write-all
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      CF_IDENTIFIER: ${{ secrets.CF_IDENTIFIER }}
      ADLIST_URLS: ${{ vars.ADLIST_URLS }}
      WHITELIST_URLS: ${{ vars.WHITELIST_URLS }}
      DYNAMIC_BLACKLIST: ${{ vars.DYNAMIC_BLACKLIST }}
      DYNAMIC_WHITELIST: ${{ vars.DYNAMIC_WHITELIST }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@main
        with:
          python-version: 3.11

      - name: Check Previous Workflow Run Status
        id: check_run
        run: |
          previous_run_status=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs?per_page=5 | jq -r '[.workflow_runs[] | select(.conclusion != null)][0].conclusion')
          if [ "$previous_run_status" == "null" ]; then
            echo "No previous successful run found."
            previous_run_status="failure"
          fi
          echo "Previous run status: $previous_run_status"
          echo "run_status=$previous_run_status" >> $GITHUB_ENV

      - name: Cache Data
        id: cache-cloudflare-data
        uses: actions/cache@main
        with:
          path: cloudflare_cache.json
          key: ${{ runner.os }}-cloudflare-data-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-cloudflare-data-
        if: env.run_status == 'success'  # Sử dụng cache nếu lần chạy trước thành công

      - name: Cloudflare Gateway Zero Trust 
        run: python -m src run

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1
